import "~/styles/globals.css";
import "mapbox-gl/dist/mapbox-gl.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

import { UserProvider } from "@auth0/nextjs-auth0/client";
import { lazy } from "react";

const BayunProvider = lazy(() => import("./auth/bayun-client"));

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "C",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <BayunProvider>{children}</BayunProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
